### PR TITLE
Use Font Awesome icons as symbols rather than loading them as sprites

### PR DESCRIPTION
**Pull request by uhafner**
Sprites are obsolete if we can reference all icons as symbols.

Action items:
- [x] Use `<l:icon>` in existing `svg-icon` tag
- [x] Fix blue coloring of icon links
- [x] Remove sprites from distribution

The sprites are still used in the SVG Java tag that requires https://github.com/jenkinsci/jenkins/pull/6659 to be merged first. So it would make sense to merge this PR without waiting for the core PR.

### CODE REVIEW

**Comment by nfalco79** [comment]
I hope with this PR is possible to remove the embedded font awesome in dependency-check plugin echart feature branch using a similar SvgTag class to generate something similar:
`<i class="fa fa-bug" style="font-size:12px; padding:6px" aria-hidden="true" />`

The i tag is what https://fontawesome.com suggest.

**Comment by uhafner** [comment]
You already can use icons using the `svg-icon` tag:

```
<j:jelly xmlns:j="jelly:core" xmlns:st="jelly:stapler" xmlns:l="/lib/layout" xmlns:fa="/font-awesome">

  [...]
  <fa:svg-icon name="bug" class="no-issues-banner"/>
  [...]

</j:jelly>
```

This PR will just replace the underlying icon loading so that symbols will be used. Symbols have the advantage that their color will change with the installed theme.

**Comment by nfalco79** [comment]
Using svg images is not able to render in a text or column like ussually we do. We have to embed the whole iconset for each bundle. Normally I think fontawesome-api plugin provide the fonts shared along all the bundle that use it.
If is not able please tell me that I will open a New Feature issue in the JIRA issue tracker

**Comment by uhafner** [comment]
> Using svg images is not able to render in a text or column like ussually we do. We have to embed the whole iconset for each bundle. Normally I think fontawesome-api plugin provide the fonts shared along all the bundle that use it.
> If is not able please tell me that I will open a New Feature issue in the JIRA issue tracker

Why not? I'm using the icons everywhere. Example: https://ci.jenkins.io/job/Plugins/job/warnings-ng-plugin/job/master/1718/

The info and warnings icons for my warnings plugin are rendered within the text. I have no plans to add the fonts as a duplicate method to render the icons.

**Pull request merged**
